export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
// Profilo MIO (utente loggato)
export const USER_MY_PROFILE_REQUEST = "USER_MY_PROFILE_REQUEST";
export const USER_MY_PROFILE_SUCCESS = "USER_MY_PROFILE_SUCCESS";
export const USER_MY_PROFILE_ERROR = "USER_MY_PROFILE_ERROR";
export const USER_MY_PROFILE_CLEAR = "USER_MY_PROFILE_CLEAR";

// Profilo di un altro utente (pubblico)
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_CLEAR = "USER_PROFILE_CLEAR";

export const USER_DATA_CLEAR = "USER_DATA_CLEAR";
export const TRENDING_REQUEST = "TRENDING_REQUEST";
export const TRENDING_SUCCESS = "TRENDING_SUCCESS";
export const TRENDING_ERROR = "TRENDING_ERROR";
export const LATESTREVIEWS_REQUEST = "LATESTREVIEWS_REQUEST";
export const LATESTREVIEWS_SUCCESS = "LATESTREVIEWS_SUCCESS";
export const LATESTREVIEWS_ERROR = "LATESTREVIEWS_ERROR";
export const TOPREVIEWERS_REQUEST = "TOPREVIEWERS_REQUEST";
export const TOPREVIEWERS_SUCCESS = "TOPREVIEWERS_SUCCESS";
export const TOPREVIEWERS_ERROR = "TOPREVIEWERS_ERROR";
export const GENRES_REQUEST = "GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_ERROR = "GENRES_ERROR";
export const PLATFORMS_REQUEST = "PLATFORMS_REQUEST";
export const PLATFORMS_SUCCESS = "PLATFORMS_SUCCESS";
export const PLATFORMS_ERROR = "PLATFORMS_ERROR";
export const LIBRARY_REQUEST = "LIBRARY_REQUEST";
export const LIBRARY_SUCCESS = "LIBRARY_SUCCESS";
export const LIBRARY_ERROR = "LIBRARY_ERROR";
export const NAVSEARCH_REQUEST = "NAVSEARCH_REQUEST";
export const NAVSEARCH_SUCCESS = "NAVSEARCH_SUCCESS";
export const NAVSEARCH_ERROR = "NAVSEARCH_ERROR";
export const NAVSEARCH_CLEAR = "NAVSEARCH_CLEAR";
export const NAVSEARCH_SET_QUERY = "NAVSEARCH_SET_QUERY";
export const GAME_DETAIL_REQUEST = "GAME_DETAIL_REQUEST";
export const GAME_DETAIL_SUCCESS = "GAME_DETAIL_SUCCESS";
export const GAME_DETAIL_ERROR = "GAME_DETAIL_ERROR";
export const UPDATE_USER_GAME_REQUEST = "UPDATE_USER_GAME_REQUEST";
export const UPDATE_USER_GAME_SUCCESS = "UPDATE_USER_GAME_SUCCESS";
export const UPDATE_USER_GAME_FAIL = "UPDATE_USER_GAME_FAIL";
export const UPDATE_USER_GAME_QUICK_REQUEST = "UPDATE_USER_GAME_QUICK_REQUEST";
export const UPDATE_USER_GAME_QUICK_SUCCESS = "UPDATE_USER_GAME_QUICK_SUCCESS";
export const UPDATE_USER_GAME_QUICK_FAIL = "UPDATE_USER_GAME_QUICK_FAIL";
export const DELETE_USER_GAME_REQUEST = "DELETE_USER_GAME_REQUEST";
export const DELETE_USER_GAME_SUCCESS = "DELETE_USER_GAME_SUCCESS";
export const DELETE_USER_GAME_FAIL = "DELETE_USER_GAME_FAIL";
export const METADATA_REQUEST = "METADATA_REQUEST";
export const METADATA_SUCCESS = "METADATA_SUCCESS";
export const METADATA_ERROR = "METADATA_ERROR";
export const ADMIN_GAMES_REQUEST = "ADMIN_GAMES_REQUEST";
export const ADMIN_GAMES_SUCCESS = "ADMIN_GAMES_SUCCESS";
export const ADMIN_GAMES_ERROR = "ADMIN_GAMES_ERROR";
export const QUESTIONNAIRE_REQUEST = "QUESTIONNAIRE_REQUEST";
export const QUESTIONNAIRE_SUCCESS = "QUESTIONNAIRE_SUCCESS";
export const QUESTIONNAIRE_ERROR = "QUESTIONNAIRE_ERROR";
export const QUESTIONNAIRE_TOGGLE_OPTION = "QUESTIONNAIRE_TOGGLE_OPTION";
export const QUESTIONNAIRE_NEXT_STEP = "QUESTIONNAIRE_NEXT_STEP";
export const QUESTIONNAIRE_PREV_STEP = "QUESTIONNAIRE_PREV_STEP";
export const QUESTIONNAIRE_SET_SUBMITTING = "QUESTIONNAIRE_SET_SUBMITTING";
export const QUESTIONNAIRE_SET_COMPLETED = "QUESTIONNAIRE_SET_COMPLETED";
export const QUESTIONNAIRE_SET_SUBMIT_ERROR = "QUESTIONNAIRE_SET_SUBMIT_ERROR";
export const QUESTIONNAIRE_RESET = "QUESTIONNAIRE_RESET";
export const QUESTIONNAIRE_STATUS_REQUEST = "QUESTIONNAIRE_STATUS_REQUEST";
export const QUESTIONNAIRE_STATUS_SUCCESS = "QUESTIONNAIRE_STATUS_SUCCESS";
export const QUESTIONNAIRE_STATUS_ERROR = "QUESTIONNAIRE_STATUS_ERROR";
export const RECOMMENDATIONS_REQUEST = "RECOMMENDATIONS_REQUEST";
export const RECOMMENDATIONS_SUCCESS = "RECOMMENDATIONS_SUCCESS";
export const RECOMMENDATIONS_ERROR = "RECOMMENDATIONS_ERROR";
export const RECOMMENDATIONS_LOAD_MORE = "RECOMMENDATIONS_LOAD_MORE";
export const RECOMMENDATIONS_RESET = "RECOMMENDATIONS_RESET";
export const FETCH_QUESTIONNAIRE_ANALYTICS_REQUEST = "FETCH_QUESTIONNAIRE_ANALYTICS_REQUEST";
export const FETCH_QUESTIONNAIRE_ANALYTICS_SUCCESS = "FETCH_QUESTIONNAIRE_ANALYTICS_SUCCESS";
export const FETCH_QUESTIONNAIRE_ANALYTICS_FAILURE = "FETCH_QUESTIONNAIRE_ANALYTICS_FAILURE";
// =========================
// ADMIN TAXONOMY - GENERI
// =========================
export const ADMIN_TAXONOMY_GENRES_FETCH_REQUEST = "ADMIN_TAXONOMY_GENRES_FETCH_REQUEST";
export const ADMIN_TAXONOMY_GENRES_FETCH_SUCCESS = "ADMIN_TAXONOMY_GENRES_FETCH_SUCCESS";
export const ADMIN_TAXONOMY_GENRES_FETCH_FAILURE = "ADMIN_TAXONOMY_GENRES_FETCH_FAILURE";

export const ADMIN_TAXONOMY_GENRE_CREATE_SUCCESS = "ADMIN_TAXONOMY_GENRE_CREATE_SUCCESS";
export const ADMIN_TAXONOMY_GENRE_UPDATE_SUCCESS = "ADMIN_TAXONOMY_GENRE_UPDATE_SUCCESS";
export const ADMIN_TAXONOMY_GENRE_DELETE_SUCCESS = "ADMIN_TAXONOMY_GENRE_DELETE_SUCCESS";

// =========================
// ADMIN TAXONOMY - TAG
// =========================
export const ADMIN_TAXONOMY_TAGS_FETCH_REQUEST = "ADMIN_TAXONOMY_TAGS_FETCH_REQUEST";
export const ADMIN_TAXONOMY_TAGS_FETCH_SUCCESS = "ADMIN_TAXONOMY_TAGS_FETCH_SUCCESS";
export const ADMIN_TAXONOMY_TAGS_FETCH_FAILURE = "ADMIN_TAXONOMY_TAGS_FETCH_FAILURE";

export const ADMIN_TAXONOMY_TAG_CREATE_SUCCESS = "ADMIN_TAXONOMY_TAG_CREATE_SUCCESS";
export const ADMIN_TAXONOMY_TAG_UPDATE_SUCCESS = "ADMIN_TAXONOMY_TAG_UPDATE_SUCCESS";
export const ADMIN_TAXONOMY_TAG_DELETE_SUCCESS = "ADMIN_TAXONOMY_TAG_DELETE_SUCCESS";

// =========================
// ADMIN TAXONOMY - METADATA
// =========================
export const ADMIN_TAXONOMY_METADATA_FETCH_REQUEST = "ADMIN_TAXONOMY_METADATA_FETCH_REQUEST";
export const ADMIN_TAXONOMY_METADATA_FETCH_SUCCESS = "ADMIN_TAXONOMY_METADATA_FETCH_SUCCESS";
export const ADMIN_TAXONOMY_METADATA_FETCH_FAILURE = "ADMIN_TAXONOMY_METADATA_FETCH_FAILURE";

export const ADMIN_TAXONOMY_METADATA_CREATE_SUCCESS = "ADMIN_TAXONOMY_METADATA_CREATE_SUCCESS";
export const ADMIN_TAXONOMY_METADATA_UPDATE_SUCCESS = "ADMIN_TAXONOMY_METADATA_UPDATE_SUCCESS";
export const ADMIN_TAXONOMY_METADATA_DELETE_SUCCESS = "ADMIN_TAXONOMY_METADATA_DELETE_SUCCESS";

// =========================
// QUESTIONNAIRE - DOMANDE ATTIVE
// =========================
export const QUESTIONNAIRE_ACTIVE_FETCH_REQUEST = "QUESTIONNAIRE_ACTIVE_FETCH_REQUEST";
export const QUESTIONNAIRE_ACTIVE_FETCH_SUCCESS = "QUESTIONNAIRE_ACTIVE_FETCH_SUCCESS";
export const QUESTIONNAIRE_ACTIVE_FETCH_FAILURE = "QUESTIONNAIRE_ACTIVE_FETCH_FAILURE";

export const QUESTIONNAIRE_ACTIVE_TOGGLE_REQUEST = "QUESTIONNAIRE_ACTIVE_TOGGLE_REQUEST";
export const QUESTIONNAIRE_ACTIVE_TOGGLE_SUCCESS = "QUESTIONNAIRE_ACTIVE_TOGGLE_SUCCESS";
export const QUESTIONNAIRE_ACTIVE_TOGGLE_FAILURE = "QUESTIONNAIRE_ACTIVE_TOGGLE_FAILURE";

// === QUESTIONNAIRE EFFECTS (OptionEffectsModal + EntitySuggestionModal) ===

// Carica gli effetti di UNA singola option
export const QUESTIONNAIRE_EFFECTS_FETCH_REQUEST = "QUESTIONNAIRE_EFFECTS_FETCH_REQUEST";
export const QUESTIONNAIRE_EFFECTS_FETCH_SUCCESS = "QUESTIONNAIRE_EFFECTS_FETCH_SUCCESS";
export const QUESTIONNAIRE_EFFECTS_FETCH_FAILURE = "QUESTIONNAIRE_EFFECTS_FETCH_FAILURE";

// Crea / aggiorna / elimina un singolo effetto
export const QUESTIONNAIRE_EFFECTS_CREATE_REQUEST = "QUESTIONNAIRE_EFFECTS_CREATE_REQUEST";
export const QUESTIONNAIRE_EFFECTS_CREATE_SUCCESS = "QUESTIONNAIRE_EFFECTS_CREATE_SUCCESS";
export const QUESTIONNAIRE_EFFECTS_CREATE_FAILURE = "QUESTIONNAIRE_EFFECTS_CREATE_FAILURE";

export const QUESTIONNAIRE_EFFECTS_UPDATE_REQUEST = "QUESTIONNAIRE_EFFECTS_UPDATE_REQUEST";
export const QUESTIONNAIRE_EFFECTS_UPDATE_SUCCESS = "QUESTIONNAIRE_EFFECTS_UPDATE_SUCCESS";
export const QUESTIONNAIRE_EFFECTS_UPDATE_FAILURE = "QUESTIONNAIRE_EFFECTS_UPDATE_FAILURE";

export const QUESTIONNAIRE_EFFECTS_DELETE_REQUEST = "QUESTIONNAIRE_EFFECTS_DELETE_REQUEST";
export const QUESTIONNAIRE_EFFECTS_DELETE_SUCCESS = "QUESTIONNAIRE_EFFECTS_DELETE_SUCCESS";
export const QUESTIONNAIRE_EFFECTS_DELETE_FAILURE = "QUESTIONNAIRE_EFFECTS_DELETE_FAILURE";

// Suggerimenti di link (EntitySuggestionModal)
export const QUESTIONNAIRE_EFFECTS_SUGGESTIONS_REQUEST = "QUESTIONNAIRE_EFFECTS_SUGGESTIONS_REQUEST";
export const QUESTIONNAIRE_EFFECTS_SUGGESTIONS_SUCCESS = "QUESTIONNAIRE_EFFECTS_SUGGESTIONS_SUCCESS";
export const QUESTIONNAIRE_EFFECTS_SUGGESTIONS_FAILURE = "QUESTIONNAIRE_EFFECTS_SUGGESTIONS_FAILURE";
export const QUESTIONNAIRE_EFFECTS_SUGGESTIONS_CLEAR = "QUESTIONNAIRE_EFFECTS_SUGGESTIONS_CLEAR";

// Domande
export const QUESTIONNAIRE_ADMIN_CREATE_QUESTION_REQUEST = "QUESTIONNAIRE_ADMIN_CREATE_QUESTION_REQUEST";
export const QUESTIONNAIRE_ADMIN_CREATE_QUESTION_SUCCESS = "QUESTIONNAIRE_ADMIN_CREATE_QUESTION_SUCCESS";
export const QUESTIONNAIRE_ADMIN_CREATE_QUESTION_FAILURE = "QUESTIONNAIRE_ADMIN_CREATE_QUESTION_FAILURE";

export const QUESTIONNAIRE_ADMIN_UPDATE_QUESTION_REQUEST = "QUESTIONNAIRE_ADMIN_UPDATE_QUESTION_REQUEST";
export const QUESTIONNAIRE_ADMIN_UPDATE_QUESTION_SUCCESS = "QUESTIONNAIRE_ADMIN_UPDATE_QUESTION_SUCCESS";
export const QUESTIONNAIRE_ADMIN_UPDATE_QUESTION_FAILURE = "QUESTIONNAIRE_ADMIN_UPDATE_QUESTION_FAILURE";

// Opzioni
export const QUESTIONNAIRE_ADMIN_CREATE_OPTION_REQUEST = "QUESTIONNAIRE_ADMIN_CREATE_OPTION_REQUEST";
export const QUESTIONNAIRE_ADMIN_CREATE_OPTION_SUCCESS = "QUESTIONNAIRE_ADMIN_CREATE_OPTION_SUCCESS";
export const QUESTIONNAIRE_ADMIN_CREATE_OPTION_FAILURE = "QUESTIONNAIRE_ADMIN_CREATE_OPTION_FAILURE";

export const QUESTIONNAIRE_ADMIN_UPDATE_OPTION_REQUEST = "QUESTIONNAIRE_ADMIN_UPDATE_OPTION_REQUEST";
export const QUESTIONNAIRE_ADMIN_UPDATE_OPTION_SUCCESS = "QUESTIONNAIRE_ADMIN_UPDATE_OPTION_SUCCESS";
export const QUESTIONNAIRE_ADMIN_UPDATE_OPTION_FAILURE = "QUESTIONNAIRE_ADMIN_UPDATE_OPTION_FAILURE";

export const QUESTIONNAIRE_ADMIN_DELETE_OPTION_REQUEST = "QUESTIONNAIRE_ADMIN_DELETE_OPTION_REQUEST";
export const QUESTIONNAIRE_ADMIN_DELETE_OPTION_SUCCESS = "QUESTIONNAIRE_ADMIN_DELETE_OPTION_SUCCESS";
export const QUESTIONNAIRE_ADMIN_DELETE_OPTION_FAILURE = "QUESTIONNAIRE_ADMIN_DELETE_OPTION_FAILURE";
